### ISSUE TITLE
Pushing forward on adding ghouls

### ISSUE THREAD

**Issue by OceanMonn** [BadDeathclaw/TG-Claw#594] opened 2019-02-18 01:46 UTC
Right currently, the new ghoul sprites are completed. We need the base coding for the race to be added with it's trade offs, etcs

+ Ghouls are resistant to toxins, very, rad resstance and heal from it.
+ Ghoul skin is fucked, they take less brute dmg for their letheary skin.
+ Ghouls can eat anything, they arent grossed out.
+ Ghouls' nervous system is fucked, they wont be as hurt from electricity.
> Ghouls can be butchered for ghoul meat, obviously.
- The leathery skin is also more prone to burn.
- Ghouls are weak, fist do less dmg and they have less overall healt.
- Normal medical items don't heal ghouls as effectively

This sorta stuff was already written off on.

**Comment by Kimochiiiiiiiiiiiiii** [comment] 2019-02-18 20:44
You realize that you contradicted youraelf, right? There's no such damage as "electrical" there's only oxygen, burn, toxin, radiation, cellular, brain and brute damage. If you say that ghouls will take less damage from things like an electrified door, then they will have resistance to burn damage, because that's the damage that being electrified causes. 

Add at least one or two negative perks on Ghoul race, I think it's got an advantage over humans. Or take out few positive perks

**Comment by OceanMonn** [comment] 2019-02-18 21:10
> You realize that you contradicted yourself, right? There's no such damage as "electrical" there's only oxygen, burn, toxin, radiation, cellular, brain and brute damage. If you say that ghouls will take less damage from things like an electrified door, then they will have resistance to burn damage, because that's the damage that being electrified causes.
> 
> Add at least one or two negative perks on Ghoul race, I think it's got an advantage over humans. Or take out few positive perks

Lad let me put this clear in tea wrote these stats up.

**Comment by AdamElTablawy** [comment] 2019-02-18 22:02
@Kimochiiiiiiiiiiiiii Wrong.

It's entirely possible to make someone take less damage from being electrocuted.

This just makes ghouls suck though these stats are ass. Weak to fighting and immune to things that never occur in the wastes.

**Comment by DIamonnd** [comment] 2019-02-18 22:21
Yeah the balancing was still being talked in the discord. **And who gives a shit if they are weak you are playing for roleplay sake not for an advantage.**

**Comment by AdamElTablawy** [comment] 2019-02-18 22:25
Shush, dlam.

Hardmode races shouldn't be implemented unless they are explicitly intended to be hardmode. If the intent of ghouls is to make them suck so that people will only play them for a challenge, go ahead. Otherwise, reconsider stats and consider no damage modifiers at all.

**Comment by DIamonnd** [comment] 2019-02-18 22:38
No yeah I'm sure it's fucking wonderful to live on as a ghoul in the Fallout universe, totally is a lifelong wish full of benefits and all the advantages of such just pile one over the other.

**Comment by AdamElTablawy** [comment] 2019-02-18 22:56
ok dlam that's nice honey but we're talking balance here

we can talk about kittens and books or whatever it is you're bitching about later

**Comment by OceanMonn** [comment] 2019-02-18 22:57
> ok dlam that's nice honey but we're talking balance here
> 
> we can talk about kittens and books or whatever it is you're bitching about later

THAT'S ENOUGH! If you wanna bitch take it to a dm, not here. As, it's been stated you deaf bastard the stats are subject to change.

**Comment by improvedname** [comment] 2019-02-18 22:58
Please keep it on topic, any off-topic comments will be deleted.

**Comment by AdamElTablawy** [comment] 2019-02-18 22:58
sorry who are you again?

no shit the stats are subject to change, that's why we're fucking discussing them right now.

**Comment by rhicora** [comment] 2019-02-18 23:00
Debate the merits and downsides of the change. This is not a place for personal attacks.

**Comment by UndeadNappist** [comment] 2019-02-18 23:05
It's a lot faster to implement it too if they're just reskinned humans. Don't forget to tinker with the species prefs in the code to get things working.

It'll be faster to implement without any mechanical changes at this time. I think with the art style - and merely including ghouls - will encourage people to be racist.

I mean, they manage it on their own without any help.

I recommend just having them straight-up heal from toxin damage exactly like slimes do, and then lower their maximum health total and speed to be something similar to feral ghouls.

The advantage of that is it's a lot easier to code in (since you can steal procs from other species or what have you. Look up slimepeople.)

**Comment by AdamElTablawy** [comment] 2019-02-18 23:06
which is exactly what i'm doing, but you know, blather on about absolute nonsense all you want.

regardless, the stats as they are are complete shit. consider not modifying ghoul stats at all-if you insist on making it roleplay related the mere fact that they are a ghoul should be sufficient enough change that they don't need statistics modifiers to make playing a ghoul harder than it should be, considering discrimination.

radiation is not present in the wastes in any format outside of player created rads at the moment and rad resistance is negligible regardless because at sufficient quantities that radiation is actually dangerous and incapacitating it will kill anyone regardless of equipment unless they are 100% rad resistant (and at ridiculous quantities it will cause burn damage, which can burn even cyborgs).

resistance to toxin is hardly enough to be worth considering.

less maximum HP just means that ghouls will always take the lifegiver trait and its boosted maximum HP to counteract the effect, OR that nobody will play ghoul, with very little inbetween. Having low health in a place like the wastes is a fast way to have your cool 'ghoul RP' cut short instantly by some random raider with a pipe.

At the moment, as designed, ghouls would be worse than even plasmamen-unclonable aliens that can't live without their suit and suck at everything. They have less HP, can barely heal, and take more damage from fire and the brute damage mitigation doesn't matter considering the lower max HP.

So before you start bitching about 'uhh deaf bastard stats are subject to change' here's a fucking change for you-don't mess with their stats at all, because they should be functionally reskinned humans, if you're relying on them creating a roleplay experience or whatever.

And modification to incoming damage types is ALWAYS a bad idea for a species.

**Comment by improvedname** [comment] 2019-02-18 23:07
Maybe easy delimbing, they ghouls after all tbh

**Comment by AdamElTablawy** [comment] 2019-02-18 23:07
@UndeadNappist Suicide. Slow movespeed is death. Nobody will want to play a race that dies easily and can barely move-ESPECIALLY the barely move part. You might claim 'uhh RP' but that'll be like, one or two people, and nobody else will because it's just straight up *not fun* to play and can't hold its own in a fight.

Easy delimbing would be fine.

**Comment by AdamElTablawy** [comment] 2019-02-18 23:09
If you REALLY want to simulate something like where ghouls are healed by radiation per canon, look into the radioactive resonance virus symptom.

There's still no rads in the wastes, but hey, if you want to be lore accurate, there's free code so you don't have to write anything new.

**Comment by Kimochiiiiiiiiiiiiii** [comment] 2019-02-18 23:13
@AdamElTablawy Read before you post your opinion, I said that the stats contradict themselves. One cannot make a race that takes less damage from being electrified and at the same time  more prone to suffer burn damage. It's like saying you're more resistant to damage from a club but take more damage from any blunt weapon.

**Comment by AdamElTablawy** [comment] 2019-02-18 23:15
@Kimochiiiiiiiiiiiiii It is entirely possible to make a race that takes less damage from being electrified overall than anyone else even if they do take more burn damage.

You are forgetting that not all multiples are the same.

If the seimens coefficient is 0.2 but the burn damage multiplier is 1.3x, then they will still take more damage than a human would if they had a seimens coefficient of 0.2, but less than a human would on average (no insulated gloves)

**Comment by DIamonnd** [comment] 2019-02-18 23:23
Hate to say Adam's got it right now, all the variables to affect with these kind of balancing and shit are already in species.dm. Wouldn't surprise me all the shit for a race that has less % of being shocked, or when it is shocked to hame more resistance to that damage would already exsist, _if anything we can just fuck it and make them always have insu, doubt ghouls got the best nervous systems honestly, and they are pretty beef jerky already so._

**Comment by AdamElTablawy** [comment] 2019-02-18 23:25
Shocks are always guaranteed if something is shocked. The power will be toned down depending on the coefficient. Budget insulated gloves are a good example of this-they may either inexplicably INCREASE the amount of damage you take from electrocution, cut it in half, negate it entirely, and so forth.

**Comment by ErwinSnowden** [comment] 2019-02-19 00:21
More damage from brute, their skin isn't leathery it's frail and weak, it's the price they pay for rapid regeneration and eternal youth. They were hit by nukes or their flesh sloughed off from radiation, they don't have real skin, only a decayed shell of flesh. Just don't fucking give them absurd buffs. Plus they should be valid to BoS/Legion since it's a player choice. Less damage from shocks doesn't make any sense according to lore but okay, lets say in the rare case you find a shocked airlock, or an electrified grille fine. Adam really has a point here, make it function like humans instead of making it a snowflake fucking race. Plus I'd love to see some pre-war ghoul RP since it's not metagame to mention the old world. :wink:

**Comment by rhicora** [comment] 2019-02-19 00:26
I'm on board with @AdamElTablawy's idea of having them as reskinned humans (maybe with only very minor tweaks, a la Bay human variants). We should get them to the point where there's no clear mechanical advantage to playing a ghoul, and it's purely a question of whether you want to roleplay it. This will avoid an outbreak of badly-played ghouls controlled by players who want a mechanical advantage.

**Comment by DIamonnd** [comment] 2019-02-19 00:34
I mean, yeah that works, only reason for the tweaks was people probably saying them being reskinned humans was just lazy work.

**Comment by OceanMonn** [comment] 2019-02-19 00:40
Or, we just pull the old code route and make em hard mode

**Comment by OceanMonn** [comment] 2019-02-19 00:49
Honestly, I'd say tweak the health and really just lower the brute damage in unarmed. That's it. Let people build the quirks from there, and maybe at a later date give the ghouls proper quirks.

**Comment by Murderfoxen** [comment] 2019-02-19 01:15
I'd love to see Ghouls added in, yes. More playable races!

 They could be really interesting as well - if we considered playing on their abilities to 'evolve' through exposure to things. A Ghoul who consumes 50 sheets of Uranium could become a glowing one, who not only resists radiation, but heals from it.

**Comment by Raze500** [comment] 2019-02-22 02:04
Solved close this reeee.

**Closed** 2019-02-26 01:43 UTC
Labels: Feature [24hr Hold], Sprites
